# Generated by Django 2.2.9 on 2020-01-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
