# Generated by Django 2.2.9 on 2020-01-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='file_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video'), ('other', 'other')], default='', max_length=256),
        ),
    ]
