# Generated by Django 2.2.9 on 2020-01-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_slide_file_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slide',
        ),
    ]
